### ISSUE TITLE
Error while printing osirix.DicomImage.completePath

### ISSUE THREAD

**Issue by xiey4** [pyosirix/pyosirix#5]
When printing the completePath for DicomImage class, I expect to see the full path of the specific dicom image in string format. Instead I get an output like this:

<built-in method completePath of osirix.DicomImage object at 0x117954840>

============== Full source code ============
import osirix

bc = osirix.currentBrowser()
seriesOrStudies = bc.databaseSelection()[0]
images = seriesOrStudies.images
print(images[0].completePath)
print(images[0].date)

============== Output ====================
<built-in method completePath of osirix.DicomImage object at 0x117954840>
2019-11-30 12:03:29

**Comment by pyosirix** [comment]
Hello.  Due to OsiriX internals, completePath acts as a method.  Therefore you need:

print(images[0].completePath())

**Comment by xiey4** [comment]
It worked. Thank you for the quick response.

Following is a note for the fields in DicomImage class with a similar behavior:
test.completePath()
test.height()
test.sopInstanceUID()
test.width()

**Comment by ghost** [comment]
Glad it worked for you and thanks for the additional info!
